provider:
  name: faas
  gateway: http://127.0.0.1:8080

functions:
  regex_go:
    lang: go
    handler: ./regex_go
    image: s8sg/regex_go

  regex_py:
    lang: python
    handler: ./regex_py
    image: s8sg/regex_py
